parameters:
  lcn_file_uploader.max_number_of_files: 100
  lcn_file_uploader.file_base_path: "%kernel.root_dir%/../web/uploads/lcn-file-uploader"
  lcn_file_uploader.web_base_path: "/uploads/lcn-file-uploader"
  lcn_file_uploader.temp_file_base_path: "%kernel.root_dir%/../web/uploads/lcn-file-uploader-temp"
  lcn_file_uploader.temp_web_base_path: "/uploads/lcn-file-uploader-temp"
  lcn_file_uploader.upload_handler.class: "Lcn\FileUploaderBundle\Services\UploadHandler"

  lcn_file_uploader.allowed_extensions:
    # Mime types are just for documentation's sake.
    # BlueImp filters by supplied extension. No checking of the
    # actual file contents is done. If your mime types are
    # configured correctly in Apache the browser will have the
    # correct expectations for each file
    - gif #image/gif
    - png #image/png
    - jpg #image/jpeg
    - jpeg #image/jpeg
    - pdf #application/pdf
    - mp3 #audio/mpeg
    - xls #application/vnd.ms-excel
    - ppt #application/vnd.ms-powerpoint
    - doc #application/msword
    - pptx #application/vnd.openxmlformats-officedocument.presentationml.presentation
    - sldx #application/vnd.openxmlformats-officedocument.presentationml.slide
    - ppsx #application/vnd.openxmlformats-officedocument.presentationml.slideshow
    - potx #application/vnd.openxmlformats-officedocument.presentationml.template
    - xlsx #application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    - xltx #application/vnd.openxmlformats-officedocument.spreadsheetml.template
    - docx #application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - dotx #application/vnd.openxmlformats-officedocument.wordprocessingml.template
    - txt #text/plain
    - rtf #text/rtf

  # Folder where originals are uploaded. This is the only folder populated for
  # uploads that are not images
  lcn_file_uploader.original:
      folder: original

  # Define sizes for image uploads
  lcn_file_uploader.sizes:
    # Depending on your further requirements, you might want to define additional image sizes.
    # However, more advanced solutions exist for image resampling, e.g.
    # https://github.com/liip/LiipImagineBundle.

    # required: "thumbnail"
    thumbnail:
      folder: thumbnail
      max_width: 200
      max_height: 150
      crop: true
    # optional: "original" - define original image size if you want to restrict the maximum image dimensions:
    original:
      folder: original
      max_width: 3000
      max_height: 2250
      crop: false

services:
    lcn.file_uploader:
        class: Lcn\FileUploaderBundle\Services\FileUploader
        arguments:
          - file_manager: '@lcn.file_uploader_file_manager'
            upload_handler_class: '%lcn_file_uploader.upload_handler.class%'
            file_base_path: '%lcn_file_uploader.file_base_path%'
            web_base_path: '%lcn_file_uploader.web_base_path%'
            temp_file_base_path: '%lcn_file_uploader.temp_file_base_path%'
            temp_web_base_path: '%lcn_file_uploader.temp_web_base_path%'
            allowed_extensions: '%lcn_file_uploader.allowed_extensions%'
            sizes: '%lcn_file_uploader.sizes%'
            original: '%lcn_file_uploader.original%'
            max_number_of_files: '%lcn_file_uploader.max_number_of_files%'

    lcn.file_uploader_file_manager:
        class: Lcn\FileUploaderBundle\Services\FileManager
        public: false


    lcn.file_uploader_cleanup_command:
        class: Lcn\FileUploaderBundle\Command\CleanupCommand
        arguments: [@lcn.file_uploader]
        tags:
            -  { name: console.command }

    lcn.twig.file_extension:
        class: Lcn\FileUploaderBundle\Twig\FileUploaderExtension
        arguments: [@lcn.file_uploader]
        tags:
            - { name: twig.extension }
