parameters:
  lcn_file_uploader.max_number_of_files: 100
  lcn_file_uploader.max_file_size: null #max file size in bytes. if set to null or omitted, system settings (e.g. php.ini) will be used
  lcn_file_uploader.file_base_path: "%kernel.root_dir%/../web/uploads/lcn-file-uploader"
  lcn_file_uploader.web_base_path: "/uploads/lcn-file-uploader"
  lcn_file_uploader.temp_file_base_path: "%kernel.root_dir%/../web/uploads/lcn-file-uploader-temp"
  lcn_file_uploader.temp_web_base_path: "/uploads/lcn-file-uploader-temp"
  lcn_file_uploader.upload_handler.class: "Lcn\FileUploaderBundle\Services\UploadHandler"
  lcn_file_uploader.assets.js.main: '/bundles/lcnfileuploader/dist/main.js'
  lcn_file_uploader.assets.css.main: '/bundles/lcnfileuploader/dist/main.css'
  lcn_file_uploader.assets.css.theme: '/bundles/lcnfileuploader/dist/theme.css'
  lcn_file_uploader.image_proxy_enabled: false

  lcn_file_uploader.allowed_extensions:
    # Mime types are just for documentation's sake.
    # BlueImp filters by supplied extension. No checking of the
    # actual file contents is done. If your mime types are
    # configured correctly in Apache the browser will have the
    # correct expectations for each file
    - gif #image/gif
    - png #image/png
    - jpg #image/jpeg
    - jpeg #image/jpeg
    - pdf #application/pdf
    - mp3 #audio/mpeg
    - xls #application/vnd.ms-excel
    - ppt #application/vnd.ms-powerpoint
    - doc #application/msword
    - pptx #application/vnd.openxmlformats-officedocument.presentationml.presentation
    - sldx #application/vnd.openxmlformats-officedocument.presentationml.slide
    - ppsx #application/vnd.openxmlformats-officedocument.presentationml.slideshow
    - potx #application/vnd.openxmlformats-officedocument.presentationml.template
    - xlsx #application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    - xltx #application/vnd.openxmlformats-officedocument.spreadsheetml.template
    - docx #application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - dotx #application/vnd.openxmlformats-officedocument.wordprocessingml.template
    - txt #text/plain
    - rtf #text/rtf

  # Define sizes for image uploads
  lcn_file_uploader.sizes:
    # Depending on your further requirements, you might want to define additional image sizes.
    # For advanced image resizing and optimization, you can optionally configure an image proxy (e.g.imgix.com).

    # required: "thumbnail"
    thumbnail:
      folder: thumbnail
      max_width: 200
      max_height: 150
      crop: true
      proxy:
        enabled: %lcn_file_uploader.image_proxy_enabled%
        url: https://my-source.imgix.com~imageUrl~
        parameters:
          w: 200
          h: 150
          crop: fit

    # optional: "original" - define original image size if you want to restrict the maximum image dimensions:
    original:
      folder: original
      max_width: 3000
      max_height: 2250
      crop: false
      proxy:
        enabled: %lcn_file_uploader.image_proxy_enabled%
        url: https://my-source.imgix.com/~imageUrl~
        parameters:
          w: 200
          h: 150
          crop: fit

services:
    lcn.file_uploader:
        class: Lcn\FileUploaderBundle\Services\FileUploader
        scope: prototype
        arguments:
          - file_namers: ['@lcn.file_uploader_file_namer_cache_buster', '@lcn.file_uploader_file_namer_hash']
            file_manager: '@lcn.file_uploader_file_manager'
            upload_handler_class: '%lcn_file_uploader.upload_handler.class%'
            file_base_path: '%lcn_file_uploader.file_base_path%'
            web_base_path: '%lcn_file_uploader.web_base_path%'
            temp_file_base_path: '%lcn_file_uploader.temp_file_base_path%'
            temp_web_base_path: '%lcn_file_uploader.temp_web_base_path%'
            allowed_extensions: '%lcn_file_uploader.allowed_extensions%'
            sizes: '%lcn_file_uploader.sizes%'
            max_number_of_files: '%lcn_file_uploader.max_number_of_files%'
            max_file_size: '%lcn_file_uploader.max_file_size%'

    lcn.file_uploader_file_manager:
        class: Lcn\FileUploaderBundle\Services\FileManager
        public: false

    lcn.file_uploader_file_namer_sanitize:
        class: Lcn\FileUploaderBundle\Services\FileNamerSanitize
        public: false

    lcn.file_uploader_file_namer_original:
        class: Lcn\FileUploaderBundle\Services\FileNamerOriginal
        public: false

    lcn.file_uploader_file_namer_hash:
        class: Lcn\FileUploaderBundle\Services\FileNamerHash
        arguments: [%secret%]
        public: false

    lcn.file_uploader_file_namer_cache_buster:
        class: Lcn\FileUploaderBundle\Services\FileNamerCacheBuster
        public: false

    lcn.file_uploader_cleanup_command:
        class: Lcn\FileUploaderBundle\Command\CleanupCommand
        arguments: [@service_container]
        tags:
            -  { name: console.command }

    lcn.file_uploader.twig_extension:
        class: Lcn\FileUploaderBundle\Twig\FileUploaderExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    lcn.file_uploader.include_assets_twig_extension:
        class: Lcn\FileUploaderBundle\Twig\FileUploaderIncludeAssetsExtension
        arguments: [@service_container, '%lcn_file_uploader.assets.js.main%', '%lcn_file_uploader.assets.css.main%', '%lcn_file_uploader.assets.css.theme%']
        tags:
            - { name: twig.extension }
